#!/bin/bash

cd $DH_ROOT # where $DH_ROOT is the root of the git repository.
export NOTEBOOK_UID=$UID
export NOTEBOOK_WORKING_DIR="$PWD" # where $PWD is the root of the git repository.
export NOTEBOOK_FUNCTION_LIBRARY_DIR="$PWD/mapping_configs/hl7v2_fhir_stu3"
export NOTEBOOK_SERVICE_ACCOUNT_FILENAME="<replace_with_service_account_json>"
export NOTEBOOK_SERVICE_ACCOUNT_DIR="<replace_with_folder_containing_service_account_json>"
export GOOGLE_APPLICATION_CREDENTIALS="$NOTEBOOK_SERVICE_ACCOUNT_DIR/$NOTEBOOK_SERVICE_ACCOUNT_FILENAME"
tee .env << EOF
NOTEBOOK_UID=$NOTEBOOK_UID
NOTEBOOK_WORKING_DIR=$NOTEBOOK_WORKING_DIR
NOTEBOOK_FUNCTION_LIBRARY_DIR=$NOTEBOOK_FUNCTION_LIBRARY_DIR
NOTEBOOK_SERVICE_ACCOUNT_FILENAME=$NOTEBOOK_SERVICE_ACCOUNT_FILENAME
NOTEBOOK_SERVICE_ACCOUNT_DIR=$NOTEBOOK_SERVICE_ACCOUNT_DIR
GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
EOF

docker-compose pull
docker-compose up --no-build